apiVersion: v1
kind: Secret
metadata:
  name: my-cluster-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
data:
  name: bXktY2x1c3Rlci1uYW1l # Base64 encoded "my-cluster-name"
  server: aHR0cHM6Ly9rM3MtYXBpLmV4YW1wbGUuY29t # Base64 encoded "https://k3s-api.example.com"
  config: ewogICJhc2giOiBbInNoYS0yNTYiXSwKICAiY2xpZW50LWNhLWZpbGUiOiAiL2V0Yy9rMy9jbHVzdGVyLWNvbmZpZy1maWxlLmlvLWNsMS1jYS5wZW0iLAogICJjbGllbnQtdGVsZXBtZXJ5IjogIi9ldGMvazIvY2x1c3Rlci1jb25maWctZmlsZS5pby1jbDEtdGVsZXBtZXRyeS5wZW0iLAogICJzZXJ2ZXIiOiAiaHR0cHM6Ly9hcGkuY2x1c3Rlci5leGFtcGxlLmNvbSIKfQo= # Base64 encoded kubeconfig
