apiVersion: v1
kind: Secret
metadata:
  name: my-cluster-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
data:
  name: bXktY2x1c3Rlci1uYW1l # Base64 encoded "my-cluster-name"
  server: aHR0cHM6Ly9rM3MtYXBpLmV4YW1wbGUuY29t # Base64 encoded "https://k3s-api.example.com"
  config: YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhv
cml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VSQ1ZF
TkRRV1V5WjBGM1NVSkJaMGxKUkZKRmNWSlFRMFJ6T1RSM1JGRlpTa3R2V2tsb2RtTk9RVkZGVEVK
UlFYZEdWRVZVVFVKRlIwRXhWVVVLUVhoTlMyRXpWbWxhV0VwMVdsaFNiR042UVdWR2R6QjVUa1JC
TUUxcVozaE9WRVY2VFdwQ1lVWjNNSHBPUkVFd1RXcFplRTVVUlRSTmFrSmhUVUpWZUFwRmVrRlNR
bWRPVmtKQlRWUkRiWFF4V1cxV2VXSnRWakJhV0UxM1oyZEZhVTFCTUVkRFUzRkhVMGxpTTBSUlJV
SkJVVlZCUVRSSlFrUjNRWGRuWjBWTENrRnZTVUpCVVVSdFExbERTSFZYTlZWUFIyNXpNVmt2T0Ux
TFdIQnpjVkJ0Tmt0WFIxUTRiR3hMY1hCRWVIVnpjWE5ITmxkd1RtWmpkMVJxU3pRclJXb0thMmh0
TUcxdlJrUXJNa2hHVW5SSGVqQXpPRTF4Tm05S2RTOXpUMDFpV0VWb2FFWjZRVzgwVDBVclkzaG9T
V1JLVWxOaWFrSlFaMlV5VkdneFUwUTFhQW80ZWxoV1NGQjRWMmRETUVoSVdrdFdlRlZyUTNaelkx
RlFSM2xPU1RSQlRERmlXSGt4VkV0U1RYVTRaMDVvU1dSdmIyZzRjbUZzTVhKWlYwVmxTR2hRQ2pC
NFJXZFplazF4ZWtad1lubDVaa0kxWkZSTlQyTlVjSGgyVFhwTlJFaHRPVkJ6UnpjMGRIRXdibTVP
UnpZdmFFMUtaRE0yYW5CWlRWbFpUVFZsUTJFS05sbHpkbVI1YzIxWWF5OHplRFpPVjJ3eE5sWnha
RU15YkU1cU16SlVNbEp1TkdVNE1qZEtZMk0yU1VKVE9HSnBXV28wT1VvclpYTndSMkpoTVhwTmJR
cFdPRUZoYkV0M1ptbDZjSGh6V21GMlFUVTJOWEJQV1dOSGVIaFVRV2ROUWtGQlIycFhWRUpZVFVF
MFIwRXhWV1JFZDBWQ0wzZFJSVUYzU1VOd1JFRlFDa0puVGxaSVVrMUNRV1k0UlVKVVFVUkJVVWd2
VFVJd1IwRXhWV1JFWjFGWFFrSlRTREptVUV0dFZXZ3daSFpSTkVJdlduZDVTRUYzTTNCUlRraFVR
VllLUW1kT1ZraFNSVVZFYWtGTloyZHdjbVJYU214amJUVnNaRWRXZWsxQk1FZERVM0ZIVTBsaU0w
UlJSVUpEZDFWQlFUUkpRa0ZSUWlzd01VcENSa2gxYkFwc1NHWTJSbVZrU0RnelVUaEZSa0l2VGxs
MWNtUlZSVlYzT1ZwWmNWWk5WRXREVDNGdVJYVlpTek5uSzNCdGF5dGFaV3BPVlZBNWRTdGpjQ3Q2
WW0xbkNtRmpSbmhqUlVwc1QyVTFaemxJVFhwaVMxcGpVVUpOTjNGRmVEaGlOVVppUWxsVFJWQkNL
elprVHpWcVlrWlROREJUUTBWUWNYWm5aRVEyWVM5QlFsUUtPV2hTWW5wMU5qSlFlak5LVlhFelVH
WktkSFp2WjFkbWRVMU1jbVZFWmxwa05uVm9WMFpHY21vd1YwSnRjR2xRYmxJemJHMHlPVTFXTUVj
eVpXMVZSUXB4VFhKWE9UWktTVzV3UjJ0dVRVNVphMVZHYjBwU1RWTkNkbUp1UlRsdVZuQlVWVW8x
U2xOdlVsRnlXVmszVW5kUU9UbEdVV1ZKU1V3d05uaEtRa0Z0Q204NE1HbDBlbUV3Y205R01tNWxk
Rmd3TWpCRk5sQTJlREZwTVhGTlYzRlJWazVpYm1nM1NXcHVaWEpVVFN0QlVIQm9PWEl4WW05SmVI
a3JVak1yWmtvS2FXdDViR0ZuU0ZCcVpqWlJDaTB0TFMwdFJVNUVJRU5GVWxSSlJrbERRVlJGTFMw
dExTMEsKICAgIHNlcnZlcjogaHR0cHM6Ly82MTEwNTM3OTI3RkYzMUE4RDA1MzI3Mzc4MkRFMEUw
QS5ncjcuYXAtc291dGgtMS5la3MuYW1hem9uYXdzLmNvbQogIG5hbWU6IGFybjphd3M6ZWtzOmFw
LXNvdXRoLTE6NzU3OTg0NjA3MDI1OmNsdXN0ZXIvZGVtby1jbHVzdGVyCi0gY2x1c3RlcjoKICAg
IGNlcnRpZmljYXRlLWF1dGhvcml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZV
UlMwdExTMHRDazFKU1VSQ1ZFTkRRV1V5WjBGM1NVSkJaMGxKUldOd04wRjZaVFZ4ZUc5M1JGRlpT
a3R2V2tsb2RtTk9RVkZGVEVKUlFYZEdWRVZVVFVKRlIwRXhWVVVLUVhoTlMyRXpWbWxhV0VwMVds
aFNiR042UVdWR2R6QjVUa1JCTUUxcWEzZFBSRUV5VGtSR1lVWjNNSHBPUkVFd1RXcGpkMDlFUlho
T1JFWmhUVUpWZUFwRmVrRlNRbWRPVmtKQlRWUkRiWFF4V1cxV2VXSnRWakJhV0UxM1oyZEZhVTFC
TUVkRFUzRkhVMGxpTTBSUlJVSkJVVlZCUVRSSlFrUjNRWGRuWjBWTENrRnZTVUpCVVVNM1kzaEhh
bVF2WjB0TVJFWmxRV1JWTUN0SVEyeHlWMnhUV0docFZsbGxiR1E0VVV4eVFubHlTbkpVV1RGdmVU
Qm5jVk41YWpSSllrVUtTMGhLUTNObGVIbFNNRGsxTW10TVNrZ3plWFpHVjJveWFqQXJVbWwxZUdF
MFJUSlNWa1F2UlZObFpXczFOVlpDZEZJcmVHZHRRbGswT0hGRmJITldMd3BsWXpsdmJITnpZMDEz
T1N0cWVqWjRhV2RMWVdOaE1IbExjMjVQTTBaWFlTdFZiUzlWTmtvcllWUlRiVGQzWlhGV1RVMUNT
M1JQYWtsUE1qQmhSekpEQ25JM1pYaENTa1JCZFdGR2NHMU9SVzU2WXpWcVdIbEpURlp4T0UxT1Yx
VktTVGRFZVRrck5FSjNRbTU1UWpsa1NtZDFibTlDV2tOd1NHaDZibkJsUW5RS1ZXeFVhRVJ6TTFa
c2RubHlPRE5zWjJrek9YUTJXVkpVTTB0cFNrY3hOWG8zTVZCbWIwWmpUbkpSTHpWNGEzQXpSVkE1
TVZJeVlVOXhkMjVyY0hoaU9BcG9NSGdyVWtjNWRIZFlTMFVyYzJVMmNDOW1VMnMwTDBGWlRHMTJR
V2ROUWtGQlIycFhWRUpZVFVFMFIwRXhWV1JFZDBWQ0wzZFJSVUYzU1VOd1JFRlFDa0puVGxaSVVr
MUNRV1k0UlVKVVFVUkJVVWd2VFVJd1IwRXhWV1JFWjFGWFFrSlVNRGd2VnpGbVJtMXRhamxXUjJG
dlMzTlpLM2R6TmxsT0x5OXFRVllLUW1kT1ZraFNSVVZFYWtGTloyZHdjbVJYU214amJUVnNaRWRX
ZWsxQk1FZERVM0ZIVTBsaU0wUlJSVUpEZDFWQlFUUkpRa0ZSUW14S2FIRXZlRlJ2ZFFwb1pGWnNa
V1l5VEd0WUwyNHhPVFozUzNSQlFXVXJXR05wTWsxTGJtVm5WRXBETDBodWNFWmhaRGtyT0RkVVZr
NWhUVXAwWlhOVWVGUm5aRTlFYmpoSUNtUTJLMmxXUjBOTU5HMXNlbUZNY2tzeU1IQlNUSEZJTUc1
TWNrOUVTa2hrY1hGaVZHaHNhRGhOVkRKeWNHeHJZVGhIYkZsVlQzQkVabTR3TURGSmVuRUtOVW96
UldkVlYybDVRVlpUZVVGSGVrcEVNblJsVGxsNFRHMHlOa2RtVVZSeVRGSTRjVGhQYkV3M1QyTmFW
MUJHWnpCRlQzWlJWbGsxUjNabEswRndjUXBsZWtoRVlWUnpUV1JpYld0T01sVk9iMGxCUkRWWlRu
QkpUV1I1TWpoalJucHBhM2d5Y0dwM1V6WkNPREpSVVZoNVQybHBOVEppWjI1RWJtVjVOMVYxQ25O
S01YbG9hVmRIVkdRMVVFSnJjVVl5UWtwalVrazJSMjlTZFZnM1dHOTJiMDUwTTBoUFlXVldPRmd2
Ymt4ME4yczBUMDlFVWpGUVYybHhiVk41ZEhFS1FraFRhbFJDTjFaNE9IRlNDaTB0TFMwdFJVNUVJ
RU5GVWxSSlJrbERRVlJGTFMwdExTMEsKICAgIHNlcnZlcjogaHR0cHM6Ly85MEVBQzI3MEY2RDQx
Njc5OUMyRUY2MjM4MURCRDVEMS5ncjcuYXAtc291dGgtMS5la3MuYW1hem9uYXdzLmNvbQogIG5h
bWU6IGFybjphd3M6ZWtzOmFwLXNvdXRoLTE6NzU3OTg0NjA3MDI1OmNsdXN0ZXIvbXktY2x1c3Rl
cgotIGNsdXN0ZXI6CiAgICBjZXJ0aWZpY2F0ZS1hdXRob3JpdHktZGF0YTogTFMwdExTMUNSVWRK
VGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVUkNWRU5EUVdVeVowRjNTVUpCWjBsSlVURkxW
MHBpYUdsR09VMTNSRkZaU2t0dldrbG9kbU5PUVZGRlRFSlJRWGRHVkVWVVRVSkZSMEV4VlVVS1FY
aE5TMkV6Vm1sYVdFcDFXbGhTYkdONlFXVkdkekI1VGtSQk1rMUVZM2hOYWtWM1RWUkdZVVozTUhw
T1JFRXlUVVJWZUUxcVJURk5WRVpoVFVKVmVBcEZla0ZTUW1kT1ZrSkJUVlJEYlhReFdXMVdlV0p0
VmpCYVdFMTNaMmRGYVUxQk1FZERVM0ZIVTBsaU0wUlJSVUpCVVZWQlFUUkpRa1IzUVhkblowVkxD
a0Z2U1VKQlVVUlliVXRuZDBOeU0yODFObkJ1UWsweFltUmFURmN6WWl0TGRFbDZkRTl4V1RseVZE
Uk1UV3M0TkRrMWFYaERaVWRDVm5WeWFXSmhTRmtLYjFWaVl6ZHdaV2t5Y0ZaU1ZFaE1OMjFCWXpG
T0t6QkxlV05FVXpaWGRYcG5jVWx4V2xBemJXSnJhRGRXZUROSlkwWkNVMEowYWxwWVozRllRVFZP
VkFwR01sUkNSemx3U0ZKSlFtcEhNblpwZERZdlRrTlhlbFJhZDJvM0sxRXJMMFZyTVRoSVMzbGhZ
aXRzU0d4RVFYWXlTblJ6WVZBeFIyWlVPRXhGTXk5aUNreGFOVGcwTDJoSU4yOXZNVWRZV2pseE5X
UlNZVWhhUlhsc2FqQkVXbVZvWkdGT1YwRTVPVWxuVTBndk1XdGlSVlZyVURSQlYxa3JWMk4wVTJs
bVRYRUtjMkpCV25KRlJHaE1SRXRxVmtjdlNXRjBNVzlsV1hvNGQxSnNSa0ZYUmxCQ2RVMU1jVTFy
T1dkWFowTTJZVk56TlRNelUwazVVeXRVWW5wNlZFcDRid3BZZG5GNlVtaHFURVExUW1KdmRUUk5a
REIxT0hkdGVIUjJiRXB3UVdkTlFrRkJSMnBYVkVKWVRVRTBSMEV4VldSRWQwVkNMM2RSUlVGM1NV
TndSRUZRQ2tKblRsWklVazFDUVdZNFJVSlVRVVJCVVVndlRVSXdSMEV4VldSRVoxRlhRa0pUZVVW
eU4yRnZkMjlrU1hoeFZYaGxUbkUzVm0xc1V6aHNTRUY2UVZZS1FtZE9Wa2hTUlVWRWFrRk5aMmR3
Y21SWFNteGpiVFZzWkVkV2VrMUJNRWREVTNGSFUwbGlNMFJSUlVKRGQxVkJRVFJKUWtGUlFtaDFZ
VmxQYjFaUlNncDFhbVpYUVhKMFZ5dGlaamhaVm5CTGFuZG9jbEl4VGpKRlZGRk5LM1JOVlUxaGVG
aE5NMlpGY0VvemNFUlRkMUZXVmlzeU9ESnNZV0ZzYlUxaVJGbEhDbTgzTDB3NFJWQjRZamRZZGlz
dlpURkdSWEJ3ZDI5c2JWWk5Oa0pLUW14SFFqSXlURXQyYTFCS01qQXlNeko0VVRZd2FVaE5kMng1
ZEdWYVZHNTFXVTBLVGt4TmJEZEJPRTFXTUZJd2RXMVVZaXRGVDFaUWFrbHJPVWhTSzA5NUwxaHZZ
UzlLTmxOcU1VUm9hRzU0VGtGVlQwNTRXbXBsVGs5SVdYUnFWVFUxV1Fwc2FHdHpaWE12V0RCTVky
NUhNMnd6V0VaU1MwTnlWblprTTJsWWJGQmtWRzh6ZGxZMFRUaEhSbXBPUkVKbVlpdGlObFlyYTBa
ek1rWmFhMjl5ZWs5VUNqSjFibFl2VjNaU2NVSlhibEZSVW10dFJXRjNLMk41Vm5odlVrY3dlRk5L
U0cxYVYxZFdTaXRxY0haRFQwTndUQzlJYm5GRGNXdDNlbmN3YkZKUWJUa0tVa3hCWkdneVRYUXpZ
Uzh3Q2kwdExTMHRSVTVFSUVORlVsUkpSa2xEUVZSRkxTMHRMUzBLCiAgICBzZXJ2ZXI6IGh0dHBz
Oi8vQkZERjdCODFCNUY2QjZGOEI3ODMwMEFENzNBQTY2NjMuZ3I3LmFwLXNvdXRoLTEuZWtzLmFt
YXpvbmF3cy5jb20KICBuYW1lOiBhcm46YXdzOmVrczphcC1zb3V0aC0xOjc1Nzk4NDYwNzAyNTpj
bHVzdGVyL3Rlc3QKLSBjbHVzdGVyOgogICAgY2VydGlmaWNhdGUtYXV0aG9yaXR5OiAvaG9tZS9i
aXR0aGFsLy5taW5pa3ViZS9jYS5jcnQKICAgIGV4dGVuc2lvbnM6CiAgICAtIGV4dGVuc2lvbjoK
ICAgICAgICBsYXN0LXVwZGF0ZTogTW9uLCAxNSBKdWwgMjAyNCAwNzowODoyNiBJU1QKICAgICAg
ICBwcm92aWRlcjogbWluaWt1YmUuc2lncy5rOHMuaW8KICAgICAgICB2ZXJzaW9uOiB2MS4zMi4w
CiAgICAgIG5hbWU6IGNsdXN0ZXJfaW5mbwogICAgc2VydmVyOiBodHRwczovLzE5Mi4xNjguNDku
Mjo4NDQzCiAgbmFtZTogbWluaWt1YmUKY29udGV4dHM6Ci0gY29udGV4dDoKICAgIGNsdXN0ZXI6
IGFybjphd3M6ZWtzOmFwLXNvdXRoLTE6NzU3OTg0NjA3MDI1OmNsdXN0ZXIvZGVtby1jbHVzdGVy
CiAgICB1c2VyOiBhcm46YXdzOmVrczphcC1zb3V0aC0xOjc1Nzk4NDYwNzAyNTpjbHVzdGVyL2Rl
bW8tY2x1c3RlcgogIG5hbWU6IGFybjphd3M6ZWtzOmFwLXNvdXRoLTE6NzU3OTg0NjA3MDI1OmNs
dXN0ZXIvZGVtby1jbHVzdGVyCi0gY29udGV4dDoKICAgIGNsdXN0ZXI6IGFybjphd3M6ZWtzOmFw
LXNvdXRoLTE6NzU3OTg0NjA3MDI1OmNsdXN0ZXIvbXktY2x1c3RlcgogICAgdXNlcjogYXJuOmF3
czpla3M6YXAtc291dGgtMTo3NTc5ODQ2MDcwMjU6Y2x1c3Rlci9teS1jbHVzdGVyCiAgbmFtZTog
YXJuOmF3czpla3M6YXAtc291dGgtMTo3NTc5ODQ2MDcwMjU6Y2x1c3Rlci9teS1jbHVzdGVyCi0g
Y29udGV4dDoKICAgIGNsdXN0ZXI6IGFybjphd3M6ZWtzOmFwLXNvdXRoLTE6NzU3OTg0NjA3MDI1
OmNsdXN0ZXIvdGVzdAogICAgdXNlcjogYXJuOmF3czpla3M6YXAtc291dGgtMTo3NTc5ODQ2MDcw
MjU6Y2x1c3Rlci90ZXN0CiAgbmFtZTogYXJuOmF3czpla3M6YXAtc291dGgtMTo3NTc5ODQ2MDcw
MjU6Y2x1c3Rlci90ZXN0Ci0gY29udGV4dDoKICAgIGNsdXN0ZXI6IG1pbmlrdWJlCiAgICBleHRl
bnNpb25zOgogICAgLSBleHRlbnNpb246CiAgICAgICAgbGFzdC11cGRhdGU6IE1vbiwgMTUgSnVs
IDIwMjQgMDc6MDg6MjYgSVNUCiAgICAgICAgcHJvdmlkZXI6IG1pbmlrdWJlLnNpZ3MuazhzLmlv
CiAgICAgICAgdmVyc2lvbjogdjEuMzIuMAogICAgICBuYW1lOiBjb250ZXh0X2luZm8KICAgIG5h
bWVzcGFjZTogZGVmYXVsdAogICAgdXNlcjogbWluaWt1YmUKICBuYW1lOiBtaW5pa3ViZQpjdXJy
ZW50LWNvbnRleHQ6IG1pbmlrdWJlCmtpbmQ6IENvbmZpZwpwcmVmZXJlbmNlczoge30KdXNlcnM6
Ci0gbmFtZTogYXJuOmF3czpla3M6YXAtc291dGgtMTo3NTc5ODQ2MDcwMjU6Y2x1c3Rlci9kZW1v
LWNsdXN0ZXIKICB1c2VyOgogICAgZXhlYzoKICAgICAgYXBpVmVyc2lvbjogY2xpZW50LmF1dGhl
bnRpY2F0aW9uLms4cy5pby92MWFscGhhMQogICAgICBhcmdzOgogICAgICAtIC0tcmVnaW9uCiAg
ICAgIC0gYXAtc291dGgtMQogICAgICAtIGVrcwogICAgICAtIGdldC10b2tlbgogICAgICAtIC0t
Y2x1c3Rlci1uYW1lCiAgICAgIC0gZGVtby1jbHVzdGVyCiAgICAgIGNvbW1hbmQ6IGF3cwogICAg
ICBlbnY6IG51bGwKICAgICAgaW50ZXJhY3RpdmVNb2RlOiBJZkF2YWlsYWJsZQogICAgICBwcm92
aWRlQ2x1c3RlckluZm86IGZhbHNlCi0gbmFtZTogYXJuOmF3czpla3M6YXAtc291dGgtMTo3NTc5
ODQ2MDcwMjU6Y2x1c3Rlci9teS1jbHVzdGVyCiAgdXNlcjoKICAgIGV4ZWM6CiAgICAgIGFwaVZl
cnNpb246IGNsaWVudC5hdXRoZW50aWNhdGlvbi5rOHMuaW8vdjFiZXRhMQogICAgICBhcmdzOgog
ICAgICAtIC0tcmVnaW9uCiAgICAgIC0gYXAtc291dGgtMQogICAgICAtIGVrcwogICAgICAtIGdl
dC10b2tlbgogICAgICAtIC0tY2x1c3Rlci1uYW1lCiAgICAgIC0gbXktY2x1c3RlcgogICAgICAt
IC0tb3V0cHV0CiAgICAgIC0ganNvbgogICAgICBjb21tYW5kOiBhd3MKICAgICAgZW52OiBudWxs
CiAgICAgIGludGVyYWN0aXZlTW9kZTogSWZBdmFpbGFibGUKICAgICAgcHJvdmlkZUNsdXN0ZXJJ
bmZvOiBmYWxzZQotIG5hbWU6IGFybjphd3M6ZWtzOmFwLXNvdXRoLTE6NzU3OTg0NjA3MDI1OmNs
dXN0ZXIvdGVzdAogIHVzZXI6CiAgICBleGVjOgogICAgICBhcGlWZXJzaW9uOiBjbGllbnQuYXV0
aGVudGljYXRpb24uazhzLmlvL3YxYmV0YTEKICAgICAgYXJnczoKICAgICAgLSAtLXJlZ2lvbgog
ICAgICAtIGFwLXNvdXRoLTEKICAgICAgLSBla3MKICAgICAgLSBnZXQtdG9rZW4KICAgICAgLSAt
LWNsdXN0ZXItbmFtZQogICAgICAtIHRlc3QKICAgICAgLSAtLW91dHB1dAogICAgICAtIGpzb24K
ICAgICAgY29tbWFuZDogYXdzCiAgICAgIGVudjogbnVsbAogICAgICBpbnRlcmFjdGl2ZU1vZGU6
IElmQXZhaWxhYmxlCiAgICAgIHByb3ZpZGVDbHVzdGVySW5mbzogZmFsc2UKLSBuYW1lOiBtaW5p
a3ViZQogIHVzZXI6CiAgICBjbGllbnQtY2VydGlmaWNhdGU6IC9ob21lL2JpdHRoYWwvLm1pbmlr
dWJlL3Byb2ZpbGVzL21pbmlrdWJlL2NsaWVudC5jcnQKICAgIGNsaWVudC1rZXk6IC9ob21lL2Jp
dHRoYWwvLm1pbmlrdWJlL3Byb2ZpbGVzL21pbmlrdWJlL2NsaWVudC5rZXkK
