apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-list
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: "https://kubernetes.default.svc"
            namespace: "application-set-generator"
            repoURL: "https://github.com/bitthalpatidar/argocd-task.git"
            path: "data/github-helm/github"
            targetRevision: "main"
            appName: "application-set-git-app"
            sourceType: "git"
          - cluster: "https://kubernetes.default.svc"
            namespace: "application-set-generator"
            repoURL: "https://github.com/bitthalpatidar/argocd-task.git"
            path: "data/github-helm/helm"
            targetRevision: "HEAD"
            appName: "application-set-helm-app"
            sourceType: "helm"
            helm:
              valueFiles:
                - values.yaml
  template:
    metadata:
      name: '{{appName}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
        {{- if eq .sourceType "helm" }}
        helm:
          valueFiles:
            {{- range .helm.valueFiles }}
            - '{{ . }}'
            {{- end }}
        {{- end }}
      destination:
        server: '{{cluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
