apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-git
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: "https://github.com/bitthalpatidar/argocd-task.git"
        revision: "main"
        directories:
          - path: "data/github-helm/*"
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: "https://github.com/bitthalpatidar/argocd-task.git"
        targetRevision: "main"
        path: '{{path}}'
      destination:
        server: "https://kubernetes.default.svc"
        namespace: 'git-generators'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
