apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: app1
            path: data/single-source
          - name: app2
            path: data/github-helm/helm
  template:
    metadata:
      name: '{{name}}' # This will be set dynamically based on the generators
    spec:
      project: default
      sources:
        - repoURL: https://github.com/bitthalpatidar/argocd-task.git
          targetRevision: HEAD
          path: data/github-helm/helm
          helm:
            releaseName: my-nginx
            valueFiles:
              - values.yaml
        - repoURL: 'https://github.com/bitthalpatidar/argocd-task.git'
          path: data/single-source
          targetRevision: HEAD
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: my-applicationset
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
