apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-applicationset-app
  namespace: argocd
spec:
  generators:
    # Generator for the first Git repository source
    - git:
        repoURL: 'https://github.com/bitthalpatidar/argocd-task.git'
        path: 'data/github-helm/github'
        # Optional: specify the revision (branch/tag/commit) to use
        ref: HEAD

    # Generator for the second Git repository source with Helm
    - git:
        repoURL: 'https://github.com/bitthalpatidar/argocd-task.git'
        path: 'data/github-helm/helm'
        # Optional: specify the revision (branch/tag/commit) to use
        ref: HEAD

  template:
    metadata:
      name: '{{name}}-{{namespace}}'
    spec:
      project: default
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: my-appicationset
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      sources:
        - git:
            repoURL: '{{item.repoURL}}'
            path: '{{item.path}}'
            ref: '{{item.ref}}'

          # Specify Helm values only for the Helm source

        -  helm:
              chart: data/single-helm  # Path to the Helm chart directory within the Git repo
              version: 0.1.0  # Specify the version of the Helm chart
              values: data/single-helm/values.yaml  # Path to values.yaml for Helm customization

