apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-and-github-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/bitthalpatidar/argocd-task.git'
        directories:
          - path: 'data/github-helm/github'
            # Optional: specify the revision (branch/tag/commit) to use
            targetRevision: HEAD
          - path: 'data/github-helm/helm'
            # Optional: specify the revision (branch/tag/commit) to use
            targetRevision: HEAD

  template:
    metadata:
      name: '{{path.basename}}-{{targetRevision}}'
    spec:
      project: default  # Specify the Argo CD project name where applications will be managed
      destination:
        server: 'https://kubernetes.default.svc'  # Kubernetes API server URL
        namespace: my-applicationset  # Namespace where applications will be deployed
      syncPolicy:
        automated:
          prune: true  # Enable pruning of resources not managed by Argo CD
          selfHeal: true  # Enable self-healing of resources
        syncOptions:
          - CreateNamespace=true  # Ensure namespace is created if not exists
      source:
        repoURL: 'https://github.com/bitthalpatidar/argocd-task.git'
        path: data/github-helm/helm
        targetRevision: HEAD
        helm:
          valueFiles:
            - values.yaml
    
