apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: git-app
            sourceType: git
          - name: helm-app
            sourceType: helm
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/bitthalpatidar/argocd-task.git
          path: data/github-helm/github
          targetRevision: HEAD
        - repoURL: https://github.com/bitthalpatidar/argocd-task.git
          targetRevision: HEAD
          path: data/github-helm/helm
          helm:
            valueFiles:
              - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: my-applicationset
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - PrunePropagationPolicy=orphan
