apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-and-git-applicationset
  namespace: argocd
spec:
  generators:
    # Generator for Helm repositories
    - helm:
        # Path to Helm charts directory relative to the repository root
        paths:
          - 'data/two-helm/helm-chart-1'
          - 'data/two-helm/helm-chart-2'

  template:
    metadata:
      # Naming pattern for each generated application
      name: '{{name}}-{{namespace}}'
    spec:
      # Project within Argo CD where the applications will be managed
      project: default
      destination:
        # Kubernetes API server URL
        server: 'https://kubernetes.default.svc'
        # Namespace where applications will be deployed
        namespace: my-applicationset
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true  # Ensure namespace is created if not exists
      sources:
        # Source for Helm charts
        - helm:
            chart: 'data/two-helm/helm-chart-1'  # Path to the Helm chart directory
            version: 0.1.0 # Version of the Helm chart if applicable
            values: 'data/two-helm/helm-chart-1/values.yaml'  # Path to values.yaml file for customization
        # Source for Git repository
        - git:
            repoURL: 'https://github.com/bitthalpatidar/argocd-task.git'  # Git repository URL
            path: 'data/single-source'  # Path within the Git repository
            ref: main  # Branch or reference within the Git repository
