apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: app1
            repoURL: https://github.com/bitthalpatidar/argocd-task.git
            revision: main
            path: data/application-set-data/app1
            cluster:
              server: https://kubernetes.default.svc
              namespace: app1-namespace
          - name: app2
            repoURL: https://github.com/bitthalpatidar/argocd-task.git
            revision: main
            path: data/application-set-data/app2
            cluster:
              server: https://kubernetes.default.svc
              namespace: app2-namespace
  template:
    metadata:
      labels:
        app: {{name}}
    spec:
      project: default
      source:
        repoURL: {{repoURL}}
        targetRevision: {{revision}}
        path: {{path}}
      destination:
        server: {{cluster.server}}
        namespace: {{cluster.namespace}}
