apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-applicationset-app
  namespace: argocd
spec:
  generators:
    # Generator for the first Git repository source
    - git:
        repoURL: 'https://github.com/bitthalpatidar/argocd-task.git'
        path: 'data/github-helm/github'
        ref: HEAD

    # Generator for the second Git repository source with Helm
    - helm:
        repoURL: 'https://github.com/bitthalpatidar/argocd-task.git'
        path: 'data/github-helm/helm'
        ref: HEAD

  template:
    metadata:
      name: '{{name}}-{{namespace}}'
    spec:
      project: default
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: my-applicationset
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      sources:
        - git:
            repoURL: '{{item.repoURL}}'
            path: '{{item.path}}'
            ref: '{{item.ref}}'

        - helm:
            chart: '{{item.path}}'  # Path to the Helm chart directory within the Git repo
            version: 0.1.0  # Specify the version of the Helm chart
            values: '{{item.path}}/values.yaml'  # Path to values.yaml for Helm customization
