apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: two-source
  namespace: argocd
spec:
  destination:
    namespace: my-task
    server: 'https://kubernetes.default.svc'
  source:
    - path: data/single-source
      repoURL: 'https://github.com/bitthalpatidar/argocd-task.git'
      targetRevision: HEAD
    - path: data/two-source
      repoURL: 'https://github.com/bitthalpatidar/argocd-task.git'
      targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
