apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: single-helm-github-source-app
  namespace: argocd
spec:
  destination:
    namespace: my-task
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/bitthalpatidar/argocd-task.git'
      path: data/github-helm/github
      targetRevision: HEAD
    - repoURL: 'https://github.com/bitthalpatidar/argocd-task.git'
      path: data/github-helm/helm
      targetRevision: HEAD
      helm:
        valueFiles:
          - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
