apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-matrix
  namespace: argocd
spec:
  generators:
    - matrix:
        appNames:
          - two-helm
        environments:
          - name: helm-chart-1
            valuesPath: "data/two-helm/helm-chart-1/values.yaml"
          - name: helm-chart-2
            valuesPath: "apps/two-helm/helm-chart-2/values.yaml"
  template:
    metadata:
      name: '{{appName}}-{{environment.name}'
    spec:
      project: default
      source:
        repoURL: "https://github.com/bitthalpatidar/argocd-task.git"
        targetRevision: "main"
        path: "data/{{appName}}/{{environment.name}}"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: 'application-set-generator'

