apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: two-helm-app
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: my-task
  source:
    # Source for Helm chart 1
    - repoURL: 'https://github.com/bitthalpatidar/argocd-task/tree/main/data/two-helm/helm-chart-1'
      path: data/two-helm/helm-chart-1
      targetRevision: HEAD
      helm:
        valueFiles:
          - data/two-helm/helm-chart-1/values.yaml  # Adjust path as per your directory structure

    # Source for Helm chart 2
    - repoURL: 'https://github.com/bitthalpatidar/argocd-task/tree/main/data/two-helm/helm-chart-2'
      path: data/two-helm/helm-chart-2
      targetRevision: HEAD
      helm:
        valueFiles:
          - data/two-helm/helm-chart-2/values.yaml  # Adjust path as per your directory structure

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
