apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: two-helm-app
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: my-task
  source:
    helm:
      # Meta Helm Chart
      chart: data/two-helm/meta-helm-chart
      version: 0.1.0
      values: data/two-helm//meta-helm-chart/values.yaml
      # Dependencies
      dependencies:
        - name: helm-chart-1
          version: 0.1.0
          repository: data/two-helm/helm-chart-1
        - name: helm-chart-2
          version: 0.1.0
          repository: data/two-helm/helm-chart-2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
