apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: two-helm-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/bitthalpatidar/argocd-task.git'
    path: data/two-helm/meta-helm-chart
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: my-task
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
