apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meta-helm-chart-app
  namespace: argocd  # Adjust namespace as needed
spec:
  project: default  # Specify the ArgoCD project name
  destination:
    server: https://kubernetes.default.svc  # Kubernetes API server URL
    namespace: my-task  # Namespace where the Helm chart will be deployed
  source:
    helm:
      # Helm chart details for meta-helm-chart
      valueFiles:
        - data/two-helm/meta-helm-chart/values.yaml  # Path to values.yaml for meta-helm-chart
      chart: data/two-helm/meta-helm-chart  # Path to meta-helm-chart directory
      version: 0.1.0  # Version of meta-helm-chart
      repository: https://github.com/bitthalpatidar/argocd-task.git  # Repository URL for meta-helm-chart
      # Optional: specify dependencies
      dependencies:
        - name: helm-chart-1
          version: 0.1.0
          repository: data/two-helm//helm-chart-1
        - name: helm-chart-2
          version: 0.1.0
          repository: data/two-helm//helm-chart-2

  syncPolicy:
    automated:
      prune: true  # Enable pruning of resources not managed by ArgoCD
      selfHeal: true  # Enable self-healing of resources
    syncOptions:
      - CreateNamespace=true  # Ensure namespace is created if not exists
